=== Omfang
<<HeleDatasettet,Hele datasettet>>

=== Beskrivelse av datakvalitet
{fkbdatasett} inneholder data fra flere kilder, se <<Datafangst>> og <<Datavedlikehold>> i denne spesifikasjonen.

{fkbdatasett} er fremstilt vha. fjernmåling og FKB-data, se <<Innledning>>.

Arealer klassifiseres i grønne og ikke-grønne arealer basert på <<NDVI,NDVI>> som er basert på <<VHR,VHR>>-satellittbilder. Det vil være varierende kvalitet fra område til område fordi VHR-datasettet er satt sammen av mange opptak fra ulike datoer og fra ulike satellitter. I utgangspunktet skal VHR-mosaikken som benyttes, være skyfri. Det kan likevel forekomme noen områder med skyer. Skyer og skygge fra terreng og skyer vil redusere nøyaktigheten på klassifikasjonen og kan medføre at kvalitetskravene ikke oppnås i slike områder.

Høydedata til arealfigurene er basert på verdiene i benyttet høydedatasett <<NDH,NDH>>. Høyde på vegetasjonen vil i utgangspunktet være like god som høydedatasettet som har blitt brukt. Vegetasjonen blir delt i arealfigurer, og i denne prosessen blir arealfigurene generalisert for å få ønsket størrelse og form. Minste kartleggingsenhet er satt til 5 m^2^, dvs. minsteareal (minste størrelse) i grønnstrukturkartet er 5 m^2^.
Bedre grunnlagsdata, mer raffinert produksjon eller nye metoder kan i framtida gi muligheter for mer nøyaktig datasett.

Beskrivelsen og kravene til kartkvalitet tar utgangspunkt i kartkontroll utført etter standarden Geodatakvalitet <<G>>. Kartkontrollen utføres som en sluttkontroll, dvs. kontroll av sluttproduktet (grønnstrukturdatasettet).
I {fkbdatasett} er det objektene Bunnsjikt, Busksjikt, Tresjikt og Grått som skal inngå i en kartkontroll.
Objekter med egenskap skygge lik 1 (dvs. arealfiguren ligger i skygge) utelates fra kartkontrollen.

=== Kvalitetskrav
Kvalitetskravene forholder seg til utvalgte kvalitetsmål fra standarden Geodatakvalitet <<G>>, vedlegg C. 
Hvert kvalitesmål i <<G>> er gitt en identifikasjon, som er angitt som referanse i tabellene under.

include::tabell_logisk_konsistens.adoc[]

include::tabell_egenskapskvalitet.adoc[]
I en kartkontroll skal det skilles mellom feilklassifisering (tilordningsfeil) mellom "grønt" og "ikke-grønt", altså mellom klassene Bunnsjikt, Busksjikt, Tresjikt på den ene siden og Grått på den andre siden.

include::tabell_fullstendighet.adoc[]
Datasettet er heldekkende innafor kartleggingsområdet, så "hull" innafor kartleggingsområdet skal ikke forekomme.

include::tabell_stedfestingsnoyaktighet.adoc[]
Det settes ikke krav til stedfestingsnøyaktighet for Bunnsjikt, Busksjikt, Tresjikt og Grått. I stedet settes det krav til klasseriktighet, altså at Bunnsjikt, Busksjikt, Tresjikt og Grått er riktig klassifisert slik at Grått ikke klassifiseres som grønt (Busksjikt, Busksjikt, Tresjikt) og motsatt, se <<Egenskapskvalitet,Tabell 3>>.

Objektene som stammer fra andre FKB-datasett har i utgangspunktet datakvalitet beskrevet i sine respektive produktspesifikasjoner/registreringsinstrukser. Disse objektene utsettes imidlertid for generalisering og segmentering når de tas inn i grønnstrukturkartet slik at deres opprinnelige stedfestingsnøyaktighet ikke nødvendigvis er fullt ut ivaretatt.