=== Omfang
<<HeleDatasettet,Hele datasettet>>

=== Beskrivelse av datakvalitet
{fkbdatasett} inneholder data fra flere kilder (se kapittel 8 og 9 i denne spesisfikasjonen). 

{fkbdatasett} er fremstilt vha. fjernmåling. Den dominerende datafangstmetoden for {fkbdatasett} er automatisk klassifisering av høyoppløslige satellittbilder fotogrammetrisk registrering.

Referere omtrentlige kontrollresultater (AKG & co).

Nøyaktigheten kan endre seg. Bedre grunnlagsdata, mer raffinert produksjon eller nye metoder kan i framtida gi muligheter for mer nøyaktige Grønnstrukturdata.

Beskrivelsen og kravene til kartkvalitet tar utgangspunkt i kartkontroll utført etter standarden Geodatakvalitet.

[NOTE]
====
For å få et godt bilde av kvaliteten til data innenfor et område må man derfor vurdere datakvaliteten (metadata) til kartobjektene. Det vil også være mulig å aggregere denne informasjonen som finnes på objektnivå opp til en beskrivelse av kvaliteten på datainnholdet i området som helhet. Det er imidlertid vanskelig å garantere datakvaliteten for FKB innenfor et område. Slik det står i FKB-AR5.

Prinsippet er at fullstendighet prioriteres foran nøyaktighet og FKB-data for et område vil derfor bestå av data med varierende grad av kvalitet. Alle data er kodet med datafangstdato og posisjonskvalitet slik at det er mulig å vurdere datakvaliteten til det enkelte dataobjekt. Det vil også være mulig å aggregere denne informasjonen som finnes på objektnivå opp til en beskrivelse av kvaliteten på datainnholdet i området som helhet. Det er imidlertid vanskelig å garantere datakvaliteten for FKB innenfor et område. Slik det står i FKB-Arealbruk.
====

=== Kvalitetskrav (Jeg har tatt utgangspunkt i kap. 8 Kvalitet i FKB Generell del)
//Bruker kap. 4.1 og 4.2 i https://sosi.geonorge.no/registreringsinstrukser/FKB-Ledning/5.0/Fotogrammetrisk_2024-01-01/#_kvalitetsklasser
include::tabell3_logisk_konsistens.adoc[]
//Dette ivaretar ingen bruk av ulovlige og gale koder, dvs. egenskapsverdier (=koder?) som ikke finnes eller f.eks. hoyde < 0 eller NDVI > 1)

include::tabell4_egenskapskonsistens.adoc[]
Ved en kartkontroll skal det skilles mellom feilklassifisering mellom "grønt" og "ikke-grønt", altså mellom klassene (Bunn, Busk, Tre) på den ene siden og Graa på den andre siden og "internt" mellom de tre "grønne" objekttypene (Bunn, Busk, Tre).
. Verst at Bunn, Busk og Tre er feilklassifisert som Graa og motsatt. (strengest krav = tillate en liten prosentandel feilklassifisert)

. Ille at Bunn er feilklassifisert som Tre og motsatt. (passe strengt krav = tillate en litt større prosentandel feilklassifisert)

. Mindre ille om Bunn/Busk er klassifisert som hhv. Busk/Bunn eller Busk/Tre er klassifisert som hhv. Tre/Busk (minst strengt krav = tillate en enda større prosentandel feilklassifisert)


[NOTE]
====
SPM: Gal ref. til Geodatakvalitet mht. 2014? Hvis det er årstall, er muligens 2015 det riktige?
Klassifikasjonsriktighet skal være <15 % feil klassifiserte egenskaper. Innebærer dette feilklassifiserte _OBJEKTTYPER_? Klassifisert som bunn, men skulle vært busk? Kan vi bruke måleenhet kvadratmeter? At xx % av totalarealet kan være feilklassifisert?
Jf. F1-score i NIBIOs interne kvalitetskontroll av grønnstruktur for Drammen (95 %), Ullensvang (86 %) og Bodø (97 %). Her er jeg imidlertid usikker på hvorfor 400 punkter er valgt (~200 i grønt område, ~200 i grått område), jf. tabell 4 i kap. 7.4.1. Geodatakvalitet.
Finner ingen informasjon om kontrollområder, kap. 7.2 i Geodatakvalitet.

Innspill fra Arn Kristian Gjersten

Vi klassifiserer arealer i grønne og ikke-grønne arealer basert på NDVI som er basert påvery high resolution (VHR) satellittdatasettet. Her kan man godt si at målet er < 15 % feil: dvs. minst 85 % av arealene klassifisert som grønne skal faktisk være det i en uavhengig kontroll. Det samme gjelder for ikke-grønne arealer. Det vil være varierende kvalitet fra område til område fordi VHR-datasettet er satt sammen av av mange opptak fra ulik dato og fra ulike satellitter. Skyer og skygge fra terreng og skyer reduserer nøyaktighet på klassifikasjonen. Det kan derfor forekomme at målet ikke oppnås i enkelte områder.

Høyde på vegetasjonen vil i utgangspunktet være like god som høydedatasettet som har blitt brukt. Vegetasjonen blir figurert i arealfigurer og i denne prosessen blir figurene generalisert for å få ønsket størrelse og form. SPM Barbi: Hva er MMU?
Høydedata til figurene er basert på verdiene i høydedatasettet, f.eks. laserdata, nasjonal digital høydemodell (NDH). SPM Barbi: Inngår EGNE laserdata eller er det bare NDH som inngår (med sine laserdata og bildematchdata, jf. https://www.kartverket.no/geodataarbeid/nasjonal-detaljert-hoydemodell/status-hoydemodell?
====

include::tabell5_fullstendighet.adoc[]
Datasettet heldekkende innafor kartleggingsområdet, så "hull" innafor kartleggingsområdet skal ikke forekomme.

[NOTE]
====
Følgende utgår?
Manglende objekter
Prosentandel manglende objekter? Er det realistisk å telle opp manglende trær, grøntområder,…? Bygninger vil jo visuelt mangle ettersom det er ønskelig at trekroner høyere enn bygninger ikke skal klippes mot bygninger.
Overskytende objekter
Prosentandel overskytende objekter? Jf. manglende.
====

include::tabell6_stedfestingsnoyaktighet.adoc[]
Det skilles mellom objekttypene
  
. som stammer fra FKB-datasett, f.eks. Veg, Vann, Bygning og Jordbruk, som har datakvalitet beskrevet i sine respektive produktssepsifikasjoner/registreringsinstrukser). MEN: Disse objekttypene utsettes for generalisering og segmentering slik at deres opprinnelige stedfestingsnøyaktighet ikke nødvendigvis er ivaretatt.

. Bunn, Busk, Tre og Graa. Her settes krav til stedfestingsnøyaktighet etter FKB-standard C/D og nøyaktighetsklasse 4 Diffuse detaljer. 

Dette settes ikke krav til høydenøyaktighet. I stedet settes det krav til klasseriktighet, altså at Bunn, Busk og Tre er riktig klassifisert slik at ikke busker er klassifiseres som bunnsjikt eller at trær klassifiseres som bukser og motsatt, se Tabell 4.

I {fkbdatasett} er det objekttypene nevnt i punkt 2, som skal inngå i en kartkontroll.
Objekttyper med egenskap iSkygge lik 1 (dvs. polygonn ligger i skygge) utelates fra kartkontrollen.


[NOTE]
====
Er dette oppnåelig?
Er stedfestingsnøyaktighet i høyde aktuelt?
Kan/skal det brukes på sjikthøyder (m) (< 4, 4–8, 8–12, 12–16, > 16)?
Hva med Bunn, Busk og Tre(m)? Droppe høydekrav og i stedet kontrollere riktig klassetilhørighet? At bunn er bunn og busk er busk osv.
====