=== Omfang
<<HeleDatasettet,Hele datasettet>>

=== Beskrivelse av datakvalitet
{fkbdatasett} inneholder data fra flere kilder, se <<Datafangst>> og <<Datavedlikehold>> i denne spesifikasjonen.

{fkbdatasett} er fremstilt vha. fjernmåling og FKB-data, se <<Innledning>>.

Arealer klassifiseres i grønne og ikke-grønne arealer basert på <<NDVI,NDVI>> som er basert på <<VHR,VHR>>-satellittbilder. Det vil være varierende kvalitet fra område til område fordi VHR-datasettet er satt sammen av mange opptak fra ulike datoer og fra ulike satellitter. Skyer og skygge fra terreng og skyer reduserer nøyaktigheten på klassifikasjonen. Det kan derfor forekomme at enkelte krav ikke oppnås i enkelte områder.

Høydedata til figurene er basert på verdiene i benyttet høydedatasett <<NDH,NDH>>. Høyde på vegetasjonen vil i utgangspunktet være like god som høydedatasettet som har blitt brukt. Vegetasjonen blir delt i arealfigurer, og i denne prosessen blir polygonene generalisert for å få ønsket størrelse og form. Minste kartleggingsenhet er satt til 5 m^2^.
Bedre grunnlagsdata, mer raffinert produksjon eller nye metoder kan i framtida gi muligheter for mer nøyaktig datasett.

Beskrivelsen og kravene til kartkvalitet tar utgangspunkt i kartkontroll utført etter standarden Geodatakvalitet <<G>>. 
I {fkbdatasett} er det objekttypene Bunnsjikt, Busksjikt, Tresjikt og Grått som skal inngå i en kartkontroll.
Objekttyper med egenskap skygge lik 1 (dvs. polygonen ligger i skygge) utelates fra kartkontrollen.

=== Kvalitetskrav
include::tabell1_logisk_konsistens.adoc[]

include::tabell2_egenskapskvalitet.adoc[]
I en kartkontroll skal det skilles mellom feilklassifisering mellom "grønt" og "ikke-grønt", altså mellom klassene (Bunnsjikt, Busksjikt, Tresjikt) på den ene siden og Grått på den andre siden.

Toleransekravene i <<Egenskapskvalitet,Tabell 2>> avspeiler forventet kvalitet i første utgave av grønnstrukturkartet. Det tilsTresjiktbes at toleransekravene vil bli sTresjiktngere i fremtidige versjoner av grønnstrukturkartet.

include::tabell3_fullstendighet.adoc[]
Datasettet er heldekkende innafor kartleggingsområdet, så "hull" innafor kartleggingsområdet skal ikke forekomme.

include::tabell4_stedfestingsnoyaktighet.adoc[]
Det settes ikke krav til stedfestingsnøyaktighet for Bunnsjikt, Busksjikt, Tresjikt og Grått. I stedet settes det krav til klasseriktighet, altså at Bunnsjikt, Busksjikt, Tresjikt og Grått er riktig klassifisert slik at Grått ikke klassifiseres som grønt (Busksjikt, Busksjikt, Tresjikt) og motsatt, se <<Egenskapskvalitet,Tabell 2>>.

Objekttypene som stammer fra FKB-datasett har i utgangspunktet datakvalitet beskrevet i sine respektive produktspesifikasjoner/regisTresjiktringsinstrukser. Disse objekttypene utsettes imidlertid for generalisering og segmentering slik at deres opprinnelige stedfestingsnøyaktighet ikke nødvendigvis er fullt ut ivaretatt.