FKB-data vedlikeholdes gjennom 3 prosesser. Det henvises til Geovekst veiledningsmateriell for nærmere beskrivelse av vedlikeholdsopplegget <<GEO-VEIL>> 

=== Vedlikeholdsinformasjon

==== Omfang 
<<HeleDatasettet,Hele datasettet>>

==== Vedlikeholdsfrekvens 
Årlig ajourhold. +
Hvert år vil datasettet bli oppdatert med nye FKB-data fra bl.a. Vei, Vann, Bygning og AR5 (jordbruksareal) samt SSB-arealbruk for områdeavgrensning, se kapittel 8.

Hvert 3. år foretas et periodisk ajourhold ved bruk av nye høyoppløselige satellittbilder.

==== Vedlikeholdsbeskrivelse 
Ajourhold foretas både årlig og hvert 3. år.

=== Vedlikeholdsinformasjon Meldinger om feil og mangler

==== Omfang
<<HeleDatasettet,Hele datasettet>>

==== Vedlikeholdsfrekvens
Kontinuerlig

==== Vedlikeholdsbeskrivelse
Kartverket mottar gjennom kundesenteret og tjenesten Rettikartet.no en del meldinger om feil og mangler i FKB fra publikum. Disse meldingene kan etter en vurdering mot andre datakilder bli lagt inn i FKB.

Også andre parter i Geovekst vil kunne ta imot meldinger om feil og avvik i kartet og oppdatere FKB på bakgrunn av disse meldingene.
